version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/kernel
    environment:
      NAME: twentythird
      ARCH: arm64
      ANDROID_VERSION: q
      CONFIG: exynos7885-a30s
      LOCALVERSION: -Twentythird
      USER: Hfib
      HOST: CircleCI

    steps:
      - checkout

      - run: |
          apt update &>/dev/null
          apt install lib32z1 git build-essential bc zip curl -y &>/dev/null
      - run: |
          curl -Lo linaro.tar.xz https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu.tar.xz
          tar -xf linaro.tar.xz
          rm linaro.tar.xz
          mv gcc-linaro-* toolchain
      - run: |
          export VERSION=`git describe --tags`
          ./build.sh auto
      - store_artifacts:
          path: ~/kernel/releases/zip
          destination: files